-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 19:07:43 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipousuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipousuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipousuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `telefone` INT NULL,
  `ddd` INT NULL,
  PRIMARY KEY (`idcontato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `descricaoPerfil` VARCHAR(225) NULL DEFAULT NULL,
  `tipousuario_id` INT(11) NOT NULL,
  `contato_idcontato` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `tipousuario_id`, `contato_idcontato`),
  INDEX `fk_usuario_tipousuario_idx` (`tipousuario_id` ASC),
  INDEX `fk_usuario_contato1_idx` (`contato_idcontato` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`area` ;

CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `area_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `area_id`),
  INDEX `fk_curso_area1_idx` (`area_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `semestre` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(45) NOT NULL,
  `previsaoConclusao` VARCHAR(45) NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `curso_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`, `curso_id`),
  INDEX `fk_aluno_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_aluno_curso1_idx` (`curso_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idendereco` INT NOT NULL,
  `logadouro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instituicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instituicao` (
  `idinstituicao` INT NOT NULL,
  `usuario_id` INT(11) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idinstituicao`, `usuario_id`),
  INDEX `fk_instituicao_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_instituicao_endereco1_idx` (`endereco_idendereco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oportunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oportunidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oportunidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `remuneracao` DECIMAL(10,0) NOT NULL,
  `cargaHoraria` DECIMAL(10,0) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `instituicao_idinstituicao` INT NOT NULL,
  `instituicao_usuario_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `instituicao_idinstituicao`, `instituicao_usuario_id`),
  INDEX `fk_oportunidade_instituicao1_idx` (`instituicao_idinstituicao` ASC, `instituicao_usuario_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_has_oportunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aluno_has_oportunidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aluno_has_oportunidade` (
  `aluno_id` INT(11) NOT NULL,
  `oportunidade_id` INT(11) NOT NULL,
  PRIMARY KEY (`aluno_id`, `oportunidade_id`),
  INDEX `fk_aluno_has_oportunidade_oportunidade1_idx` (`oportunidade_id` ASC),
  INDEX `fk_aluno_has_oportunidade_aluno1_idx` (`aluno_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`area_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`area_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`area_has_endereco` (
  `area_id` INT(11) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`area_id`, `endereco_idendereco`),
  INDEX `fk_area_has_endereco_endereco1_idx` (`endereco_idendereco` ASC),
  INDEX `fk_area_has_endereco_area1_idx` (`area_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`curso_has_oportunidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`curso_has_oportunidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`curso_has_oportunidade` (
  `curso_id` INT(11) NOT NULL,
  `oportunidade_id` INT(11) NOT NULL,
  PRIMARY KEY (`curso_id`, `oportunidade_id`),
  INDEX `fk_curso_has_oportunidade_oportunidade1_idx` (`oportunidade_id` ASC),
  INDEX `fk_curso_has_oportunidade_curso1_idx` (`curso_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
